### ISSUE TITLE
syntaxerror while running permutation_peakcaller

### ISSUE THREAD

**Issue by parhampey** [Xinglab/CLAM#22]
Hey I am trying to call peaks with the permutation_callpeak subcommand but am getting the following error. Any idea what is going on? 

Traceback (most recent call last):
  File "/Users/parhampeyda/opt/anaconda3/bin/CLAM", line 4, in <module>
    __import__('pkg_resources').run_script('CLAM==1.2.0', 'CLAM')
  File "/Users/parhampeyda/opt/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/parhampeyda/opt/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/parhampeyda/opt/anaconda3/lib/python3.8/site-packages/CLAM-1.2.0-py3.8.egg/EGG-INFO/scripts/CLAM", line 326, in <module>
  File "/Users/parhampeyda/opt/anaconda3/lib/python3.8/site-packages/CLAM-1.2.0-py3.8.egg/EGG-INFO/scripts/CLAM", line 69, in main
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1342, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1316, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1297, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 414, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 649, in spec_from_file_location
  File "<frozen zipimport>", line 191, in get_filename
  File "<frozen zipimport>", line 713, in _get_module_code
  File "<frozen zipimport>", line 647, in _compile_source
  File "/Users/parhampeyda/opt/anaconda3/lib/python3.8/site-packages/CLAM-1.2.0-py3.8.egg/CLAM/permutation_peakcaller.py", line 157
    (unibam_file, multibam_file, child_gene_list, gene_annot, 
    ^
SyntaxError: invalid syntax

**Comment by parhampey** [comment]
Looks like this was because I was running the software with Python 3. When I switched to Python 2 I don't get this error anymore. However, I am getting another error

  File "build/bdist.macosx-10.6-x86_64/egg/CLAM/permutation_peakcaller.py", line 62, in parser
IndexError: list index out of range

Not sure what is going on now.

**Comment by wkdeng** [comment]
Thanks for point it out. Previously, we require both multi-mapped reads and uniquely mapped reads (generated by preprocessor), now only 1 input bam is allowed.
